name: depth-completion
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.7.6
  - pytorch=1.4.0
  - torchvision
  - ninja
  - numpy
  - opencv
  - pillow
  - pip
  - setuptools
  - six
  - tensorboard
  - tqdm
  - pip:
    - argparse
    - colorlog
    - cycler
    - decorator
    - easydict
    - efficientnet-pytorch
    - future
    - imageio
    - matplotlib
    - pyyaml
    - scikit-image
    - termcolor
    - yacs