model:
  arch: "DM-LRN"
  max_channels: 256
  modulation: "SPADE"
  activation: ("LeakyReLU", [0.2, True] )
  upsample: "bilinear"
  use_crp: True
  criterion: (("DepthL1Loss",  .5), ("DepthL2Loss",  .5), )
  predict_log_depth: False
  mask_encoder_ksize: 3


  backbone:
    arch: "efficientnet-b3"
    imagenet: True
    norm_layer: ""
    multi_scale_output: True

train:
  batch_size: 24
  lr: 0.0001
